package symbols

// symbols is a map of common currency symbols.
// Source: https://gist.github.com/manishtiwari25/d3984385b1cb200b98bcde6902671599
var symbols = map[string]string{
	"ALL": "Lek",  // Lek (Albania)
	"AFN": "؋",    // Afghani (Afghanistan)
	"ARS": "$",    // Peso (Argentina)
	"AWG": "ƒ",    // Guilder (Aruba)
	"AUD": "$",    // Dollar (Australia)
	"AZN": "₼",    // Manat (Azerbaijan)
	"BSD": "$",    // Dollar (Bahamas)
	"BBD": "$",    // Dollar (Barbados)
	"BYR": "p.",   // Ruble (Belarus)
	"BZD": "BZ$",  // Dollar (Belize)
	"BMD": "$",    // Dollar (Bermuda)
	"BOB": "$b",   // Boliviano (Bolivia)
	"BAM": "KM",   // Convertible Marka (Bosnia and Herzegovina)
	"BWP": "P",    // Pula (Botswana)
	"BGN": "лв",   // Lev (Bulgaria)
	"BRL": "R$",   // Real (Brazil)
	"BND": "$",    // Darussalam Dollar (Brunei)
	"KHR": "៛",    // Riel (Cambodia)
	"CAD": "$",    // Dollar (Canada)
	"KYD": "$",    // Dollar (Cayman)
	"CLP": "$",    // Peso (Chile)
	"CNY": "¥",    // Yuan Renminbi (China)
	"COP": "$",    // Peso (Colombia)
	"CRC": "₡",    // Colon (Costa Rica)
	"HRK": "kn",   // Kuna (Croatia)
	"CUP": "₱",    // Peso (Cuba)
	"CZK": "Kč",   // Koruna (Czech Republic)
	"DKK": "kr",   // Krone (Denmark)
	"DOP": "RD$",  // Peso (Dominican Republic)
	"EGP": "£",    // Pound (Egypt)
	"SVC": "$",    // Colon (El Salvador)
	"EEK": "kr",   // Kroon (Estonia)
	"EUR": "€",    // Euro (Euro Member)
	"FKP": "£",    // Pound (Falkland Islands)
	"FJD": "$",    // Dollar (Fiji)
	"GEL": "₾",    // Lari (Georgia)
	"GHC": "¢",    // Cedis (Ghana)
	"GIP": "£",    // Pound (Gibraltar)
	"GTQ": "Q",    // Quetzal (Guatemala)
	"GGP": "£",    // Pound (Guernsey)
	"GYD": "$",    // Dollar (Guyana)
	"HNL": "L",    // Lempira (Honduras)
	"HKD": "$",    // Dollar (Hong Kong)
	"HUF": "Ft",   // Forint (Hungary)
	"ISK": "kr",   // Krona (Iceland)
	"INR": "₹",    // Rupee (India)
	"IDR": "Rp",   // Rupiah (Indonesia)
	"IRR": "﷼",    // Rial (Iran)
	"IMP": "£",    // Pound (Isle of Man)
	"ILS": "₪",    // Shekel (Israel)
	"JMD": "J$",   // Dollar (Jamaica)
	"JPY": "¥",    // Yen (Japan)
	"JEP": "£",    // Pound (Jersey)
	"KZT": "лв",   // Tenge (Kazakhstan)
	"KPW": "₩",    // Won (Korea (North))
	"KRW": "₩",    // Won (Korea (South))
	"KGS": "лв",   // Som (Kyrgyzstan)
	"LAK": "₭",    // Kip (Laos)
	"LVL": "Ls",   // Lat (Latvia)
	"LBP": "£",    // Pound (Lebanon)
	"LRD": "$",    // Dollar (Liberia)
	"LTL": "Lt",   // Litas (Lithuania)
	"MKD": "ден",  // Denar (Macedonia)
	"MYR": "RM",   // Ringgit (Malaysia)
	"MUR": "₨",    // Rupee (Mauritius)
	"MXN": "$",    // Peso (Mexico)
	"MNT": "₮",    // Tughrik (Mongolia)
	"MZN": "MT",   // Metical (Mozambique)
	"NAD": "$",    // Dollar (Namibia)
	"NPR": "₨",    // Rupee (Nepal)
	"ANG": "ƒ",    // Antilles Guilder (Netherlands)
	"NZD": "$",    // Dollar (New Zealand)
	"NIO": "C$",   // Cordoba (Nicaragua)
	"NGN": "₦",    // Naira (Nigeria)
	"NOK": "kr",   // Krone (Norway)
	"OMR": "﷼",    // Rial (Oman)
	"PKR": "₨",    // Rupee (Pakistan)
	"PAB": "B/.",  // Balboa (Panama)
	"PYG": "Gs",   // Guarani (Paraguay)
	"PEN": "S/.",  // Nuevo Sol (Peru)
	"PHP": "₱",    // Peso (Philippines)
	"PLN": "zł",   // Zloty (Poland)
	"QAR": "﷼",    // Riyal (Qatar)
	"RON": "lei",  // New Leu (Romania)
	"RUB": "₽",    // Ruble (Russia)
	"SHP": "£",    // Pound (Saint Helena)
	"SAR": "﷼",    // Riyal (Saudi Arabia)
	"RSD": "Дин.", // Dinar (Serbia)
	"SCR": "₨",    // Rupee (Seychelles)
	"SGD": "$",    // Dollar (Singapore)
	"SBD": "$",    // Dollar (Solomon Islands)
	"SOS": "S",    // Shilling (Somalia)
	"ZAR": "R",    // Rand (South Africa)
	"LKR": "₨",    // Rupee (Sri Lanka)
	"SEK": "kr",   // Krona (Sweden)
	"CHF": "CHF",  // Franc (Switzerland)
	"SRD": "$",    // Dollar (Suriname)
	"SYP": "£",    // Pound (Syria)
	"TWD": "NT$",  // New Dollar (Taiwan)
	"THB": "฿",    // Baht (Thailand)
	"TTD": "TT$",  // Dollar (Trinidad and Tobago)
	"TRL": "₺",    // Lira (Turkey)
	"TVD": "$",    // Dollar (Tuvalu)
	"UAH": "₴",    // Hryvna (Ukraine)
	"GBP": "£",    // Pound (United Kingdom)
	"USD": "$",    // Dollar (United States)
	"UYU": "$U",   // Peso (Uruguay)
	"UZS": "лв",   // Som (Uzbekistan)
	"VEF": "Bs",   // Bolivar Fuerte (Venezuela)
	"VND": "₫",    // Dong (Viet Nam)
	"YER": "﷼",    // Rial (Yemen)
	"ZWD": "Z$",   // Dollar (Zimbabwe)
}

// GetSymbol returns currency symbol (e.g "$") matching the given currency code (e.g. "USD").
// If no matching symbols found, the given currency code is returned.
func GetSymbol(code string) string {
	symbol, found := symbols[code]
	if found {
		return symbol
	} else {
		return code
	}
}
