services:
  groshi-app:
    container_name: groshi-app
    build:
      context: ./
    environment:
      # todo: use docker secret instead of some env vars!
      GROSHI_HOST: 0.0.0.0
      GROSHI_PORT: 8080
      GROSHI_JWT_SECRET_KEY: secret123

      GROSHI_POSTGRES_HOST: groshi-postgres
      GROSHI_POSTGRES_PORT: 5432
      GROSHI_POSTGRES_USER: groshi
      GROSHI_POSTGRES_PASSWORD: password123
      GROSHI_POSTGRES_DATABASE: groshi

      GIN_MODE: debug

    depends_on:
      - groshi-postgres

    ports:
      - "80:8080"

  groshi-postgres:
    container_name: groshi-postgres
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: groshi
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: groshi
    volumes:
      - ./.postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
