services:
  groshi-app:
    container_name: groshi-app
    build:
      context: ./

    environment:
      GROSHI_HOST: 0.0.0.0
      GROSHI_PORT: 8080
      GIN_MODE: debug

      GROSHI_JWT_SECRET_KEY_FILE: /run/secrets/app/jwt_secret_key

      GROSHI_MONGO_HOST: groshi-mongo
      GROSHI_MONGO_PORT: 5432
      GROSHI_MONGO_USERNAME_FILE: /run/secrets/mongo/username
      GROSHI_MONGO_PASSWORD_FILE: /run/secrets/mongo/password
      GROSHI_MONGO_DATABASE_FILE: /run/secrets/mongo/database


    depends_on:
      - groshi-mongo

    ports:
      - "80:8080"

    secrets:
      - app
      - mongo
  groshi-mongo:
    container_name: wg-node-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo/username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo/password
      MONGO_INITDB_DATABASE_FILE: /run/secrets/mongo/database

    volumes:
      - ./.mongo-data:/data/db

    secrets:
      - mongo

    #    ports:
    #      - "27017:27017"

secrets:
  app:
    file: ./secrets/app

  postgres:
    file: ./secrets/mongo