definitions:
  handler.authLoginParams:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handler.authLoginResponse:
    properties:
      expires:
        example: "2034-03-20T12:57:38+02:00"
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IldlbGwsIGlmIHlvdSBjYW4gcmVhZCB0aGlzLCB0aGVuIHlvdSBkZWZpbmV0ZWx5IHdvdWxkIGxpa2UgdGhpcyBvbmU6IGh0dHBzOi8veW91dHUuYmUvZFF3NHc5V2dYY1EifQ.1ervhGZz1m6xiHR447rbwh8W1sfATF2qYudOtNWhkkw
        type: string
    type: object
  handler.userCreateParams:
    properties:
      password:
        example: my-secret-password
        type: string
      username:
        example: jieggii
        type: string
    type: object
  handler.userCreateResponse:
    properties:
      username:
        example: jieggii
        type: string
    type: object
  handler.userDeleteResponse:
    properties:
      username:
        example: jieggii
        type: string
    type: object
  handler.userGetResponse:
    properties:
      username:
        example: jieggii
        type: string
    type: object
  model.Error:
    properties:
      error_message:
        example: example error message (who cares)
        type: string
    type: object
info:
  contact: {}
  description: "\U0001F4C9 groshi - damn simple tool to keep track of your finances."
  license:
    name: MIT
    url: https://github.com/groshi-project/groshi/blob/master/LICENSE
  title: groshi
  version: 0.1.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates user, generates and returns valid JSON Web Token
      parameters:
      - description: Username and password
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handler.authLoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/handler.authLoginResponse'
        "400":
          description: Invalid request body format or invalid request params
          schema:
            $ref: '#/definitions/model.Error'
        "403":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Authenticate user
      tags:
      - auth
  /user:
    delete:
      consumes:
      - application/json
      description: Deletes the current user and returns its username
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/handler.userDeleteResponse'
        "400":
          description: Invalid request body format or invalid request params
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Delete the current user
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Returns information about the current user
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/handler.userGetResponse'
        "400":
          description: Invalid request body format or invalid request params
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      security:
      - Bearer: []
      summary: Retrieve information about the current user
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Creates a new user and returns its username
      parameters:
      - description: Username and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.userCreateParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/handler.userCreateResponse'
        "400":
          description: Invalid request body format or invalid request params
          schema:
            $ref: '#/definitions/model.Error'
        "409":
          description: User with such username already exists
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Create a new user
      tags:
      - user
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
